language: python

matrix:
 include:
  - python: 2.7
    env: MPL_VERSION="<=2.2.3"
  - python: 3.5
    env: MPL_VERSION="<=2.2.3"
  - python: 3.5
    env: MPL_VERSION=""
  - python: 3.6
    env: MPL_VERSION="<=2.2.3"
  - python: 3.6
    env: MPL_VERSION=""

install:
 - pip install --upgrade pip
 - pip install --upgrade setuptools
 - pip install numpy
 - pip install pytest
 - pip install --force-reinstall "matplotlib${MPL_VERSION}"

script:
 - python setup.py install
 - python -m pytest
